
class secrets{

  String _CONSUMER_KEY = 'iJcIOyhSSpCOY6MYWkkWIQonl';
  String _CONSUMER_SECRET = 'fC8SEPIUvnjdBsx8fQjhyjuYR1Be1jddoGyvPxmqRDJoV2wfz6';
  String _ACCESS_TOKEN = '853580389398523905-i1um3KovOOSZNAIILZ2LrGUHDGgLyci';
  String _ACCESS_TOKEN_SECRET = 'NjXgtH1dWDEa72Y05Ell7N3q8KgFdajIFZywmNtfa1CIS';

  String get CONSUMER_KEY => _CONSUMER_KEY;

  String get CONSUMER_SECRET => _CONSUMER_SECRET;

  String get ACCESS_TOKEN_SECRET => _ACCESS_TOKEN_SECRET;

  String get ACCESS_TOKEN => _ACCESS_TOKEN;


}